import "./globals.css";
import { Outfit } from "next/font/google";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={`${inter.className} min-h-screen flex flex-col`}>
            <NavBar />
            {children}
            <Footer />              
        </body>
      </html>
  );
}
